name: okx-trading
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2024.3.11=hecd8cb5_0
  - certifi=2024.2.2=py310hecd8cb5_0
  - ciso8601=2.3.0=py310h6c40b1e_0
  - libblas=3.9.0=21_osx64_openblas
  - libcblas=3.9.0=21_osx64_openblas
  - libcxx=16.0.6=hd57cbcb_0
  - libffi=3.4.4=hecd8cb5_0
  - libgfortran=5.0.0=13_2_0_h97931a8_2
  - libgfortran5=13.2.0=h2873a65_2
  - liblapack=3.9.0=21_osx64_openblas
  - libopenblas=0.3.26=openmp_hfef2a42_0
  - libta-lib=0.4.0=h0dc2134_2
  - llvm-openmp=17.0.6=hb6ac08f_0
  - ncurses=6.4=hcec6c5f_0
  - openssl=3.0.13=hca72f7f_0
  - pycparser=2.21=pyhd3eb1b0_0
  - python=3.10.13=h5ee71fb_0
  - python_abi=3.10=2_cp310
  - readline=8.2=hca72f7f_0
  - setuptools=68.0.0=py310hecd8cb5_0
  - sqlite=3.41.2=h6c40b1e_0
  - ta-lib=0.4.28=py310hf0b6da5_0
  - tk=8.6.12=h5d9f67b_0
  - typing-extensions=4.9.0=py310hecd8cb5_1
  - typing_extensions=4.9.0=py310hecd8cb5_1
  - wheel=0.41.2=py310hecd8cb5_0
  - xz=5.4.5=h6c40b1e_0
  - zlib=1.2.13=h4dc903c_0
  - pip:
      - aiofiles==23.2.1
      - aiohttp==3.9.0
      - aiosignal==1.3.1
      - amqp==5.2.0
      - annotated-types==0.5.0
      - anyio==3.7.1
      - appdirs==1.4.4
      - appnope==0.1.3
      - apscheduler==3.10.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asgiref==3.7.2
      - asttokens==2.2.1
      - async-lru==2.0.4
      - async-property==0.2.2
      - async-timeout==4.0.3
      - asyncstdlib==3.10.9
      - atomicwrites==1.4.1
      - attrs==23.1.0
      - automat==22.10.0
      - babel==2.12.1
      - backcall==0.2.0
      - backtrader==1.9.78.123
      - beautifulsoup4==4.12.2
      - billiard==4.2.0
      - bleach==6.0.0
      - blinker==1.7.0
      - brotli==1.1.0
      - browser-cookie3==0.19.1
      - celery==5.3.6
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - chromedriver-autoinstaller==0.6.3
      - click==8.1.7
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - comm==0.1.4
      - constantly==15.1.0
      - contourpy==1.1.1
      - cryptography==41.0.7
      - curl-cffi==0.5.10
      - cycler==0.12.1
      - debugpy==1.6.7.post1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - distro==1.8.0
      - duckduckgo-search==3.9.8
      - et-xmlfile==1.1.0
      - exceptiongroup==1.1.3
      - executing==1.2.0
      - fastapi==0.110.1
      - fastjsonschema==2.18.0
      - flask==3.0.0
      - fonttools==4.43.1
      - forex-python==1.8
      - fqdn==1.5.1
      - frozendict==2.3.8
      - frozenlist==1.4.0
      - fuzzywuzzy==0.18.0
      - g4f==0.1.9.0
      - greenlet==3.0.1
      - h11==0.14.0
      - h2==4.1.0
      - haversine==2.8.0
      - hpack==4.0.0
      - html5lib==1.1
      - httpcore==1.0.2
      - httptools==0.6.0
      - httpx==0.25.2
      - hyperframe==6.0.1
      - hyperlink==21.0.0
      - idna==3.4
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - incremental==22.10.0
      - influxdb==5.3.1
      - influxdb-client==1.39.0
      - ipykernel==6.25.1
      - ipython==8.14.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.0
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jaraco-classes==3.3.0
      - jedi==0.19.0
      - jinja2==3.1.2
      - js2py==0.74
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-client==8.3.0
      - jupyter-console==6.6.3
      - jupyter-core==5.3.1
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.2
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.5
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.24.0
      - jupyterlab-widgets==3.0.8
      - keyring==24.2.0
      - kiwisolver==1.4.5
      - kombu==5.3.6
      - loguru==0.7.2
      - lxml==4.9.3
      - lz4==4.3.2
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - mistune==3.0.1
      - mmh3==4.0.1
      - more-itertools==10.1.0
      - msgpack==1.0.7
      - multidict==6.0.4
      - multitasking==0.0.11
      - mysql-connector-python==8.3.0
      - nbclient==0.8.0
      - nbconvert==7.7.4
      - nbformat==5.9.2
      - nest-asyncio==1.5.7
      - notebook==7.0.2
      - notebook-shim==0.2.3
      - numpy==1.25.2
      - okex==0.1.6
      - openai==1.3.3
      - openpyxl==3.1.2
      - outcome==1.3.0.post0
      - overrides==7.4.0
      - packaging==23.1
      - pandas==2.0.3
      - pandas-datareader==0.10.0
      - pandas-ta==0.3.14b0
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathlib-mate==1.3.1
      - patsy==0.5.6
      - peewee==3.17.0
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.1.0
      - pip==24.0
      - platformdirs==3.10.0
      - prettytable==3.9.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - psutil==5.9.5
      - psycopg2-binary==2.9.9
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-arkose-generator==0.0.0.2
      - pycryptodome==3.19.0
      - pycryptodomex==3.19.0
      - pydantic==2.3.0
      - pydantic-core==2.6.3
      - pyexecjs==1.5.1
      - pygments==2.16.1
      - pyjsparser==2.7.1
      - pyopenssl==23.3.0
      - pyparsing==3.1.1
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-json-logger==2.0.7
      - python-okx==0.2.6
      - pytz==2023.3
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - reactivex==4.0.4
      - redis==5.0.3
      - referencing==0.30.2
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.9.2
      - schedule==1.2.1
      - scipy==1.11.4
      - selenium==4.15.2
      - send2trash==1.8.2
      - simplejson==3.19.2
      - six==1.16.0
      - sniffio==1.3.0
      - socksio==1.0.0
      - sortedcontainers==2.4.0
      - soupsieve==2.4.1
      - sqlalchemy==1.4.51
      - sqlalchemy-mate==1.4.28.4
      - stack-data==0.6.2
      - starlette==0.37.2
      - statsmodels==0.14.1
      - terminado==0.17.1
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.9.0
      - trio==0.23.1
      - trio-websocket==0.11.1
      - tvdatafeed==1.2.1
      - twisted==22.10.0
      - tzdata==2023.3
      - tzlocal==5.2
      - undetected-chromedriver==3.5.4
      - uri-template==1.3.0
      - urllib3==1.26.7
      - uszipcode==1.0.1
      - uvicorn==0.23.2
      - uvloop==0.17.0
      - vine==5.1.0
      - waitress==2.1.2
      - watchfiles==0.20.0
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.2
      - websockets==11.0.3
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.8
      - wsproto==1.2.0
      - yarl==1.9.3
      - yfinance==0.2.31
      - zipp==3.16.2
      - zope-interface==6.0
prefix: /Users/rain/anaconda3/envs/okx-trading
